#include "stdio.h"

/**
 * main - Start here
 * Desc - Each new term in the Fibonacci sequence
 * is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will
 * be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89. By considering
 * the terms in the Fibonacci sequence whose values do not
 * exceed 4,000,000, write a program that finds and prints
 * the sum of the even-valued terms, followed by a new line.
 *
 * Return: 0
 */

int main(void)
{
	long int prev, next, temp, sum;

	prev = 0;
	temp = 0;
	next = 1;
	sum = 0;

	while (temp < 4000000)
	{
		temp = prev + next;
		prev = next;
		next = temp;

		if (temp % 2 == 0)
		{
			sum += temp;
		}

	}
	printf("%ld\n", sum);

	return (0);
}

